const express = require('express')
const { UploadResume, upload, get_resume } = require('../controller/uploadResume')
const { SignIn, SigninUserData } = require('../controller/signin')
const { SignUp } = require('../controller/signup')
const { VerifyToken } = require('../middleware/verifyUser')
const { JobDescription, GetJobDescription } = require('../controller/getJobDescription')
const { GetJobDescriptionId } = require('../controller/resumeResults')
const router = express.Router()
router.put('/uploadResume', upload.single("resume"), UploadResume)
router.post('/signin', SignIn)
router.post('/signup', SignUp)
router.post('/verifyToken', VerifyToken, SigninUserData)
router.post('/get_job_description', JobDescription)
router.post('/get_resume', get_resume)
router.get('/job_description', GetJobDescription)
router.get('/job_description_id',GetJobDescriptionId)
module.exports = router